#!/bin/bash
#
# copy this to your vagrant box to be able to reload courses

cd /edx/app/edxapp/edx-platform

# sudo /edx/bin/python.edxapp ./manage.py lms --settings aws import --nostatic /vagrant $*
sudo /edx/bin/python.edxapp ./manage.py lms --settings aws import /vagrant $*
